config/routes.rb
Whitehat::Application.routes.draw do
  root 'home#index'
  
  get '/login',  :to => 'sessions#new',     :as => 'login'
  get '/logout', :to => 'sessions#destroy', :as => 'logout'

  match '/auth/:provider/callback', :to => 'sessions#create', :via => [:get, :post]
  match '/auth/failure',            :to => 'sessions#failure', :via => [:get, :post]

  resources :issues do
    resources :comments
  end
end

app/models/collaborator.rb
class Collaborator < ActiveRecord::Base
  belongs_to :issue
  attr_accessible :github_user_id
  validates_presence_of :issue_id, :github_user_id
  
  def user
    User.where(:uid => github_user_id).first
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :body, :user_id
  validates_presence_of :body

  belongs_to :user
  belongs_to :issue

end

app/models/issue.rb
class Issue < ActiveRecord::Base
  attr_accessible :repository, :title, :body
  validates_presence_of :repository, :title, :body, :user_id

  belongs_to :user
  has_many :collaborators
  has_many :comments
  
  after_create :create_collaborators
  
  def github_url
    "https://github.com/#{repository}"
  end
  
  def create_collaborators
    user.github_client.collaborators(repository).each do |user|
      puts user
      collaborators.create(:github_user_id => user.id)
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :uid, :provider, :nickname, :email, :gravatar_id, :token

  has_many :issues
  has_many :comments
  
  def self.find_by_nickname!(nickname)
    where(['lower(nickname) =?', nickname.downcase]).first!
  end

  def self.create_from_auth_hash(hash)
    create!(extract_info(hash))
  end

  def self.find_by_auth_hash(hash)
    conditions = extract_info(hash).slice(:provider, :uid)
    where(conditions).first
  end
  
  def github_profile
    "https://github.com/#{nickname}" if nickname.present?
  end
  
  def github_client
    @github_client ||= Octokit::Client.new(:login => nickname, :oauth_token => token, :auto_traversal => true)
  end
  
  def to_param
    nickname
  end
  
  def to_s
    nickname
  end
  
  def collaborating_issues
    Collaborator.where(:github_user_id => uid).map(&:issue)
  end
  
  private
  
  def self.extract_info(hash)
    provider    = hash.fetch('provider')
    uid         = hash.fetch('uid')
    nickname    = hash.fetch('info',{}).fetch('nickname')
    email       = hash.fetch('info',{}).fetch('email', nil)
    gravatar_id = hash.fetch('extra',{}).fetch('raw_info',{}).fetch('gravatar_id', nil)
    token       = hash.fetch('credentials', {}).fetch('token')

    {
      :provider => provider,
      :token => token,
      :uid => uid,
      :nickname => nickname,
      :email => email,
      :gravatar_id => gravatar_id
    }
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?

  private
  def ensure_logged_in
    unless logged_in?
      flash[:notice] = "You must be logged in to view this content."

      session[:pre_login_destination] = "http://#{request.host}#{request.path}"
      redirect_to login_path
    end
  end

  def current_user
    @current_user ||= User.find_by_id(session[:user_id])
  end

  def logged_in?
    !!current_user
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_filter :ensure_logged_in
  
  def show
    @comment = Comment.find(params[:id])
  end
  
  def new
    @comment = Comment.new
  end
  
  def create
    issue = Issue.find(params[:issue_id])
    @comment = issue.comments.build(params[:comment].merge(user_id: current_user.id))

    if @comment.save
      redirect_to issue
    else
      render :new
    end
  end
  
  def edit
    @comment = Comment.find(params[:id])
  end
  
  def update
    @comment = Comment.find(params[:id])
    if @comment.update_attributes(params[:comment])
      redirect_to @comment
    else
      render :edit
    end
  end

  def destroy
    flash[:notice] = 'You succesfully deleted a comment.'
    comment = Comment.find(params[:id])
    comment.destroy
    redirect_to comment.issue
  end
  
  private
  def comment_params
    params.require(:comment).permit(:body, :user_id)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    redirect_to issues_path if logged_in?
  end
end

app/controllers/issues_controller.rb
class IssuesController < ApplicationController
  before_filter :ensure_logged_in

  def index
    @reported_issues = current_user.issues
    @collaborating_issues = current_user.collaborating_issues
  end
  
  def show
    @issue = Issue.find(params[:id])
  end
  
  def new
    @issue = Issue.new
  end
  
  def create
    @issue = current_user.issues.build(params[:issue])
    if @issue.save
      redirect_to @issue
    else
      render :new
    end
  end
  
  def edit
    @issue = Issue.find(params[:id])
  end
  
  def update
    @issue = Issue.find(params[:id])
    if @issue.update_attributes(params[:issue])
      redirect_to @issue
    else
      render :edit
    end
  end
  
  private
  def issue_params
    params.require(:issue).permit(:repository, :title, :body)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    redirect_to "/auth/#{ Rails.application.config.default_provider }"
  end

  def create
    auth_hash = request.env['omniauth.auth']
    user      = User.find_by_auth_hash(auth_hash) ||
                  User.create_from_auth_hash(auth_hash)

    session[:user_id] = user.id

    redirect_to issues_path and return unless pre_login_destination
    redirect_to pre_login_destination
  end

  def destroy
    session.delete(:user_id)
    redirect_to root_path
  end

  def failure
    flash[:notice] = params[:message]
    redirect_to root_path
  end

private

  def pre_login_destination
    session[:pre_login_destination]
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def gravatar_url(digest, size = '80')
    digest ||= ''
    "https://secure.gravatar.com/avatar/#{digest}.png?s=#{size}&d=https://a248.e.akamai.net/assets.github.com%2Fimages%2Fgravatars%2Fgravatar-user-420.png"
  end
end

app/views/comments/_comment.html.haml
%p
  %b= comment.user.nickname
  commented
  %span
    = time_ago_in_words(comment.created_at)
    ago
%p= GitHub::Markdown.render_gfm(comment.body).html_safe

app/views/comments/_form.html.haml
= form.text_area :body
= form.submit 'Comment'

app/views/comments/edit.html.haml
.col-md-8
  %h1 Editing comment
  
  = form_for @comment, :url => edit_issue_comment_path do |form|
    = render form

app/views/comments/new.html.haml
.col-md-8
  %h1 New comment
  
  = form_for @comment, :url => issue_comments_path do |form|
    = render form

app/views/home/index.html.haml
.col-md-8
  %h1 Private Issues yo
  
  %p Blurb
  
  %p
    = link_to 'Login with Github', login_path

app/views/issues/_form.html.haml
= form.input :repository, :placeholder => 'username/repository'
= form.input :title
= form.input :body
= form.submit 'Submit new issue'

app/views/issues/_issue.html.haml
%h2= link_to issue.title, issue
%p
  On
  = issue.repository

app/views/issues/_issue_comments.html.haml
- for comment in @issue.comments
  = render comment
  - if current_user == comment.user
    = link_to "Edit", edit_issue_comment_path(@issue.id, comment.id)
    = link_to "Delete", issue_comment_path(@issue.id, comment.id), :method => 'delete'

app/views/issues/edit.html.haml
.col-md-8
  %h1 Editing Issue
  
  = simple_form_for @issue, :html => { :class => 'form-vertical' } do |form|
    = render form

app/views/issues/index.html.haml
.col-md-8
  %h1 Reported issues
  
  = render @reported_issues
  
  = link_to 'Report an issue', new_issue_path, :class => 'btn btn-primary'

.col-md-4  
  %h1 Issues you can see
  = render @collaborating_issues
    

app/views/issues/new.html.haml
.col-md-8
  %h1 New Issue
  
  = simple_form_for @issue, :html => { :class => 'form-vertical' } do |form|
    = form.input :repository
    = form.input :title
    = form.input :body
    = form.submit 'Submit new issue'

app/views/issues/show.html.haml
.col-md-8
  - if flash[:notice]
    .notice= flash[:notice]
  %h1
    = @issue.title
    on
    = link_to @issue.repository, @issue.github_url
  = GitHub::Markdown.render_gfm(@issue.body).html_safe
  = link_to 'Edit', edit_issue_path(@issue)

.col-md-8
  = render 'issue_comments'

.col-md-8
  = link_to "New comment", new_issue_comment_path(@issue)

app/views/layouts/application.html.haml
!!!
%html{lang: "en"}
  %head
    %meta{charset: "utf-8"}/
    %meta{content: "width=device-width, initial-scale=1.0", name: "viewport"}/
    %meta{content: "", name: "description"}/
    %meta{content: "", name: "author"}/
    %title Whitehat
    = stylesheet_link_tag    "application", media: "all"
    = csrf_meta_tags
  %body
    .container
      .masthead
        %h3.text-muted Whitehat

      .row
        = yield

      .footer
        %p © Company 2013
    = javascript_include_tag "application"